steps:
  - script: |
      $(activate.command) pyjanitor-dev
      pycodestyle .
      black --check -l 79 .
      pytest .
      jupyter nbconvert --config nbconvert_config.py --execute --template full
    displayName: 'Run tests, check code style, programmatically execute notebooks'
